# Generated by Django 6.0.6 on 2026-06-09 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.order'),
        ),
    ]
