# Generated by Django 6.0.6 on 2026-06-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ordersitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
