# Generated by Django 6.0.6 on 2026-06-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_description_alter_product_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersitem',
            old_name='unit_price',
            new_name='price',
        ),
    ]
