# Generated by Django 6.0.6 on 2026-06-16 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_unit_price_ordersitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='store.product'),
        ),
    ]
